# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 904fb64de3892d8a59b3e92c126245f494ec07917acb07e135191523351f703ee7f48d900412926e4c70d1746ec4c85180988c6b60491d1425a1a5e863abb115

test:
  secret_key_base: fe228238b33d7050015dc320424fdf74a0311ac9f23155db063d873edc8ceeeb91a61adff0cc3a2fd018b8485fe447e01c8c2ab300894e85e4dafa3f320a9953

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
